# Generated by Django 5.0.2 on 2024-02-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("serving_size", models.CharField(max_length=64)),
                ("calories", models.IntegerField()),
                ("total_fat_dv", models.IntegerField()),
                ("saturated_fat_dv", models.IntegerField()),
                ("trans_fat", models.IntegerField()),
                ("cholesterol_dv", models.IntegerField()),
                ("sodium_dv", models.IntegerField()),
                ("total_carbohydrates_dv", models.IntegerField()),
                ("dietary_fiber_dv", models.IntegerField()),
                ("total_sugars", models.IntegerField()),
                ("added_sugars_dv", models.IntegerField()),
                ("protein", models.IntegerField()),
                ("vitamin_d_dv", models.IntegerField()),
                ("calcium_dv", models.IntegerField()),
                ("iron_dv", models.IntegerField()),
                ("potassium_dv", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="MealieApp.fooditem",
                    ),
                ),
            ],
        ),
    ]
