# Generated by Django 4.2.10 on 2024-02-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MealieApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fooditem",
            options={
                "verbose_name": "Food Item Entry",
                "verbose_name_plural": "Food Item Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="protein",
            field=models.FloatField(),
        ),
    ]
