# Generated by Django 4.2.10 on 2024-02-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MealieApp", "0003_rename_trans_fat_fooditem_trans_fat_dv"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="quantity",
            field=models.FloatField(default=0),
        ),
    ]
