# Generated by Django 4.2.10 on 2024-03-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MealieApp", "0005_alter_fooditem_total_sugars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="added_sugars_dv",
            field=models.IntegerField(default=0, verbose_name="Added Sugars (%DV)"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="calcium_dv",
            field=models.IntegerField(default=0, verbose_name="Calcium (%DV)"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="calories",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="cholesterol_dv",
            field=models.IntegerField(default=0, verbose_name="Cholesterol (%DV)"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="dietary_fiber_dv",
            field=models.IntegerField(default=0, verbose_name="Dietary Fiber (%DV)"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="iron_dv",
            field=models.IntegerField(default=0, verbose_name="Iron (%DV)"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="potassium_dv",
            field=models.IntegerField(default=0, verbose_name="Potassium (%DV)"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="protein",
            field=models.FloatField(default=0, verbose_name="Protein"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="saturated_fat_dv",
            field=models.IntegerField(default=0, verbose_name="Saturated Fat (%DV)"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="sodium_dv",
            field=models.IntegerField(default=0, verbose_name="Sodium (%DV)"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="total_carbohydrates_dv",
            field=models.IntegerField(
                default=0, verbose_name="Total Carbohydrates (%DV)"
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="total_fat_dv",
            field=models.IntegerField(default=0, verbose_name="Total Fat (%DV)"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="total_sugars",
            field=models.FloatField(default=0, verbose_name="Total Sugars"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="trans_fat_dv",
            field=models.IntegerField(default=0, verbose_name="Trans Fat (%DV)"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="vitamin_d_dv",
            field=models.IntegerField(default=0, verbose_name="Vitamin D (%DV)"),
        ),
    ]
